#!/usr/bin/env bash
# requires GNU bash 4.0+
# author: Mort Yao <soi@mort.ninja>

LOG=/dev/stderr

# ANSI colors
AC_RESET="\033[0m"
AC_INFO=
AC_COMMAND="\033[94m\033[1m"
AC_WARNING="\033[93m\033[1m"
AC_ERROR="\033[91m\033[1m"
AC_INTERACTIVE="\033[92m\033[1m"
AC_MESSAGE="\033[96m\033[1m"

help() {
    read -r -d '' USAGE << 'EOF'
usage: hit <filename> [<args>]
EOF
    echo -E "$USAGE" > $LOG
}

if [ $# -eq 0 ]; then
    help && exit 0
fi

# read arguments
FILENAME=$1
shift && ARGS=$@

if [ ! -r "$FILENAME" ]; then
    echo -e $AC_ERROR"[fatal] file not found: $FILENAME"$RESET > $LOG
    exit 1
fi
EXTENSION=${FILENAME##*.} && EXTENSION=${EXTENSION,,}
MAINNAME=${FILENAME} && MAINNAME=${MAINNAME%.*}
case $EXTENSION in
    'java' ) # Java
        LANG="Java"
        if [ -z "$IMPL" ]; then IMPL="javac"; fi
        COMMAND="$IMPL"
        TARGET="$MAINNAME.class"
        ;;
    'groovy' ) # Groovy
        LANG="Groovy"
        if [ -z "$IMPL" ]; then IMPL="groovyc"; fi
        COMMAND="$IMPL"
        TARGET="$MAINNAME.class"
        ;;
    'scala' ) # Scala
        LANG="Scala"
        if [ -z "$IMPL" ]; then IMPL="scalac"; fi
        COMMAND="$IMPL"
        TARGET="$MAINNAME.class"
        ;;
    'cs' ) # C#
        LANG="C#"
        if [ -z "$IMPL" ]; then IMPL="mcs"; fi
        COMMAND="$IMPL"
        TARGET="$MAINNAME.exe"
        ;;
    'vb' ) # Visual Basic .NET
        LANG="Visual Basic .NET"
        if [ -z "$IMPL" ]; then IMPL="vbnc"; fi
        COMMAND="$IMPL"
        TARGET="$MAINNAME.exe"
        ;;
    'fs' | 'fsx' ) # F#
        LANG="F#"
        if [ -z "$IMPL" ]; then IMPL="fsharpc"; fi
        COMMAND="$IMPL"
        TARGET="$MAINNAME.exe"
        ;;
    'for' | 'f90' | 'f95' | 'f03' | 'f08' ) # Fortran
        LANG="Fortran"
        if [ -z "$IMPL" ]; then IMPL="gfortran"; fi
        COMMAND="$IMPL -o $MAINNAME"
        TARGET="$MAINNAME"
        ;;
    'bas' ) # BASIC
        LANG="BASIC"
        if [ -z "$IMPL" ]; then IMPL="fbc"; fi
        COMMAND="$IMPL"
        TARGET="$MAINNAME"
        ;;
    'pas' ) # Pascal
        LANG="Pascal"
        if [ -z "$IMPL" ]; then IMPL="fpc"; fi
        COMMAND="$IMPL"
        TARGET="$MAINNAME"
        ;;
    'adb' ) # Ada
        LANG="Ada"
        if [ -z "$IMPL" ]; then IMPL="gnatmake"; fi
        COMMAND="$IMPL"
        TARGET="$MAINNAME"
        ;;
    'c' ) # C
        LANG="C"
        if [ -z "$IMPL" ]; then IMPL="gcc"; fi
        COMMAND="$IMPL -o $MAINNAME"
        TARGET="$MAINNAME"
        ;;
    'cpp' | 'cc' | 'cxx' | 'c++' ) # C++
        LANG="C++"
        if [ -z "$IMPL" ]; then IMPL="g++"; fi
        COMMAND="$IMPL -o $MAINNAME"
        TARGET="$MAINNAME"
        ;;
    'sml' ) # Standard ML
        LANG="Standard ML"
        if [ -z "$IMPL" ]; then IMPL="mosmlc"; fi
        COMMAND="$IMPL -o $MAINNAME"
        TARGET="$MAINNAME"
        ;;
    'ml' ) # OCaml
        LANG="OCaml"
        if [ -z "$IMPL" ]; then IMPL="ocamlopt"; fi
        COMMAND="$IMPL -o $MAINNAME"
        TARGET="$MAINNAME"
        ;;
    'hs' ) # Haskell
        LANG="Haskell"
        if [ -z "$IMPL" ]; then IMPL="ghc"; fi
        COMMAND="$IMPL"
        TARGET="$MAINNAME"
        ;;
    'idr' ) # Idris
        LANG="Idris"
        if [ -z "$IMPL" ]; then IMPL="idris"; fi
        COMMAND="$IMPL -o $MAINNAME"
        TARGET="$MAINNAME"
        ;;
    # TODO
    ######
    * )
        echo -e $AC_ERROR"[fatal] unknown file extension: .$EXTENSION"$RESET > $LOG
        exit 1
        ;;
esac

INFO="[compiling]\n"
INFO=$INFO"language: \t$LANG\n"
INFO=$INFO"source: \t$FILENAME\n"
SIZE_WC=`wc $FILENAME | tr -s ' '`
SIZE_BYTES=`echo ${SIZE_WC} | cut -d' ' -f3`
SIZE_LINES=`echo ${SIZE_WC} | cut -d' ' -f1`
INFO=$INFO"source size: \t$SIZE_BYTES bytes, $SIZE_LINES lines\n"
INFO=$INFO"last modified: \t`date -r \"$FILENAME\"`\n"
if [ -r "$TARGET" ]; then
    INFO=$INFO"last compiled: \t`date -r \"$TARGET\"`\n"
fi
# display log
echo -e $AC_INFO$INFO$AC_RESET > $LOG

# execute command
COMMAND="$COMMAND $FILENAME $ARGS"
echo -e $AC_COMMAND\$ $COMMAND$AC_RESET > $LOG
echo -ne $AC_WARNING > $LOG
$COMMAND
EXIT_CODE=$?
echo -ne $AC_RESET > $LOG

exit $EXIT_CODE
